before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - bash examples/vrpc-react-todos-1/test/test.sh prod
  - bash examples/vrpc-react-todos-2/test/test.sh prod

notifications:
  email:
    - burkhard.heisen@heisenware.com
